spring:
  application:
    name: springboot-ci-cd
  datasource:
    #url: jdbc:postgresql://postgres:5433/mydb // ONLY FOR RUN LCOALLY WITH RUN BUTTON
    url: jdbc:postgresql://localhost:5433/mydb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis
    port: 6379

